site:
  title: DEV Satisfactory Modding Documentation
  start_page: satisfactory-modding::index.adoc

  ## Used for dev
  url: http://localhost:8000

content:
  sources:
    # Used for dev
    - url: ./
      branches: HEAD
    
    # To add additional sites, use the format below
    # You will probably want to mark this file assume-unchanged in git if so
    # https://dev.to/nickraphael/git-assume-unchanged-for-when-you-want-git-to-ignore-an-edit-for-a-while-2lig

    #- url: G:\Projects\Satisfactory\Mods\FicsItNetworks
    #  branches: HEAD
    #  edit_url: '{web_url}/blob/{refname}/{path}'
    #  start_path: docs

ui:
  bundle:
    url: https://gitlab.com/vilsol/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
