site:
  title: Satisfactory Modding Documentation
  start_page: satisfactory-modding::index.adoc

  ## Used for prod
  url: https://docs.ficsit.app

  ## Used for dev
  #url: http://localhost:8000

content:
  sources:
    ## Used for prod
    - url: https://github.com/satisfactorymodding/Documentation.git
      branches: master, v3.9.1, v3.8.0, v3.7.0, v3.6.1, v3.5.1, v3.4.1, v3.3.2, v3.1.1, v2.2.1, v2.1.1, v2.0.0, v1.0.2
      edit_url: '{web_url}/blob/{refname}/{path}'

    ## Used for dev
    #- url: ./
    #  branches: HEAD

    - url: https://github.com/CoderDE/FicsIt-Networks.git
      branches: master
      edit_url: '{web_url}/blob/{refname}/{path}'
      start_path: docs

    - url: https://github.com/Mrhid6Mods/RRD_Docs.git
      branches: master
      edit_url: '{web_url}/blob/{refname}/{path}'
      start_path: docs

    - url: https://github.com/Feyko/TweakIt.git
      branches: docs
      edit_url: '{web_url}/blob/{refname}/{path}'
      start_path: docs

    - url: https://github.com/porisius/FicsitRemoteMonitoring.git
      branches: main
      edit_url: '{web_url}/blob/{refname}/{path}'
      start_path: docs

    - url: https://github.com/Kyri123/KMods-Docs.git
      branches: main
      edit_url: '{web_url}/blob/{refname}/{path}'
      start_path: docs

    - url: https://github.com/budak7273/ContentLib_Documentation.git
      branches: main
      edit_url: '{web_url}/blob/{refname}/{path}'
      start_path: /

ui:
  bundle:
    url: https://gitlab.com/vilsol/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
